# Site settings
title: Rodger's test
email: acrite22@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome test site.  Best test site ever yo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acrite22.github.io" # the base hostname & protocol for your site
twitter_username: acrite22
github_username:  acrite22

# Build settings
markdown: kramdown
